version: '2'

services:
    mysql_polymorphic_relations:
        image: ambientum/mysql:5.7
        container_name: mysql_polymorphic_relations
        volumes:
          - ./mysql:/var/lib/mysql
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=123456
          - MYSQL_PASSWORD=123456
          - MYSQL_DATABASE=root
          - MYSQL_USER=root

    app_polymorphic_relations:
        image: ambientum/php:7.0-caddy
        container_name: app_polymorphic_relations
        volumes:
          - .:/var/www/app
        ports:
          - "80:8080"
        links:
          - mysql_polymorphic_relations

    php_polymorphic_relations:
        image: phpmyadmin/phpmyadmin
        container_name: php_polymorphic_relations
        links:
          - mysql_polymorphic_relations:db
        ports:
          - 8080:80
